[package]
name = "zeldalike"
version = "0.2.0"
authors = ["BitSpittle <bit.spittle@gmail.com>"]
edition = "2018"

[dependencies]
game2d = { path = "../game2d" }

[dependencies.ggez]
version = "*" # Reuse ggez from game2d
features = ["cargo-resource-root"]
